name: sppi
channels:
- pytorch
- defaults
- conda-forge
- anaconda
dependencies:
- python>=3.5
- pytorch
- graphviz
- matplotlib
- numpy
- scikit-learn
- scikit-image
- scipy
- torchvision
- tqdm
- seaborn
- pandas
- parse
- jupyter